version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    networks:
      - teleport  
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/mamad/apps/portainer/:/data

traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    depends_on: 
      -step-ca
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
    networks:
      - teleport         
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
  web-secure:
    address: ":443"  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/mamad/apps/traefik:/data
    labels:
        - "traefik.enable=true"  


networks:
  teleport:
    external: true
