version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    networks:
      - teleport  
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/mamad/apps/portainer/:/data

traefik:
    image: traefik:latest
    container_name: traefik
    depends_on: 
      -step-ca
    networks:
      - teleport         
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
entryPoints:
  web:
    address: ":80"

  web-secure:
    address: ":443"  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/mamad/apps/traefik:/data
    labels:
        - "traefik.enable=true"  


networks:
  teleport:
    external: true
